from collections.abc import Iterator

from pxr import Sdf

class SchemaBase: ...

class Attribute:
    def Get(self) -> Sdf.AssetPath: ...
    def GetPath(self) -> Sdf.Path: ...
    def GetPropertyStack(self) -> tuple[Sdf.PropertySpec, ...]: ...
    def GetTypeName(self) -> Sdf.ValueTypeName: ...

class Prim:
    def __bool__(self) -> bool: ...
    def GetAppliedSchemas(self) -> tuple[str, ...]: ...
    def GetAttribute(self, name: str) -> Attribute: ...
    def GetAttributes(self) -> tuple[Attribute, ...]: ...
    def GetPath(self) -> Sdf.Path: ...
    def IsA(self, schema_type: type[SchemaBase]) -> bool: ...

class Stage:
    @classmethod
    def Open(cls, path: str) -> Stage | None: ...
    def GetDefaultPrim(self) -> Prim: ...
    def GetPrimAtPath(self, path: str) -> Prim: ...
    def GetRootLayer(self) -> Sdf.Layer: ...
    def GetUsedLayers(self) -> tuple[Sdf.Layer, ...]: ...
    def Traverse(self) -> Iterator[Prim]: ...

class TimeCode:
    @classmethod
    def Default(cls) -> TimeCode: ...
