from collections.abc import Sequence

from pxr import Usd

class Mesh(Usd.SchemaBase):
    def __init__(self, prim: Usd.Prim) -> None: ...
    def GetPointsAttr(self) -> Usd.Attribute: ...

class _Range3d:
    def GetMin(self) -> Sequence[float]: ...
    def GetMax(self) -> Sequence[float]: ...

class _BBox3d:
    def ComputeAlignedBox(self) -> _Range3d: ...

class BBoxCache:
    def __init__(self, time: Usd.TimeCode, purposes: list[str]) -> None: ...
    def ComputeWorldBound(self, prim: Usd.Prim) -> _BBox3d: ...

def GetStageUpAxis(stage: Usd.Stage) -> str: ...
def GetStageMetersPerUnit(stage: Usd.Stage) -> float: ...
