from pxr import Usd

class Material(Usd.SchemaBase):
    def __bool__(self) -> bool: ...
    def GetPrim(self) -> Usd.Prim: ...

class Relationship: ...

class MaterialBindingAPI:
    def __init__(self, prim: Usd.Prim) -> None: ...
    def ComputeBoundMaterial(self) -> tuple[Material, Relationship]: ...
